#!/bin/bash
info=$(upower -i /org/freedesktop/UPower/devices/battery_BAT0)
state=$(echo "$info" | grep 'state' | awk '{print $2}')
powerlevel=$(echo "$info" | grep 'percent' | awk '{print $2}')
echo ${state:0:1}: $powerlevel
