#!/bin/sh

apps="$HOME/___apps"

echo "# DELETE THIS LINE and delete lines you want to KEEP" > $apps
yay -Qet | awk '{ print $1 }' >> $apps
vim $apps
[ -s $apps ] && yay -Rs $(cat $apps) || echo "No packages to delete."
yes | yay -Scc
rm $apps
[ "$1" == "-n" ] || neofetch
