#!/bin/sh

apps="$HOME/___apps"

echo "# DELETE THIS LINE and delete lines you want to KEEP" > $apps
yay -Qet | awk '{ print $1 }' >> $apps
vim $apps
yay -Rs $(cat $apps)
yes | yay -Scc
rm $apps
neofetch
